"""
MLStation page builder
----------------------
Creates (or refreshes) every section and topic landing page from ONE site map.

    python build_pages.py

Safe to re-run: it only overwrites pages that still contain the AUTO marker.
Your own articles are never touched. Delete the marker line in a page if you
want to customise it by hand.
"""
from pathlib import Path

AUTO = "<!-- AUTO-GENERATED by build_pages.py : delete this line to edit by hand -->"

# section slug : (title, icon, tagline, [(group, [(slug, title, icon, description), ...]), ...])
SITE = {
    "ml": ("Machine Learning", "cpu",
           "Models that learn from data: from linear baselines to deep networks, explained with the math and the code.",
           [("Foundations", [
               ("supervised", "Supervised Learning", "bullseye", "Regression and classification with labeled data."),
               ("unsupervised", "Unsupervised Learning", "diagram-2", "Clustering, dimensionality reduction and hidden structure."),
               ("deep-learning", "Deep Learning", "layers", "Neural networks, CNNs, transformers and training at depth."),
               ("feature-engineering", "Feature Engineering", "sliders", "Turning raw data into signals a model can learn from."),
           ]),
            ("Practice", [
               ("algorithms", "Algorithms", "braces", "Core ML algorithms derived step by step, then implemented."),
               ("evaluation", "Evaluation", "clipboard-check", "Metrics, validation strategies and honest error analysis."),
               ("tools", "Tools", "tools", "scikit-learn, PyTorch, XGBoost and the modern ML toolkit."),
           ])]),
    "ai": ("Artificial Intelligence", "stars",
           "Language models, retrieval, agents and perception: how modern AI systems work and how to build them.",
           [("Models", [
               ("llms", "Large Language Models", "chat-square-text", "How LLMs are trained, aligned, evaluated and served."),
               ("prompt-engineering", "Prompt Engineering", "pencil-square", "Reliable prompting patterns, structure and evaluation."),
               ("computer-vision", "Computer Vision", "eye", "Image classification, detection, segmentation and generation."),
               ("nlp", "NLP", "translate", "Tokenization, embeddings and classic language tasks."),
           ]),
            ("Systems", [
               ("rag", "RAG", "database", "Retrieval-augmented generation: chunking, embeddings, ranking."),
               ("agentic-ai", "Agentic AI", "robot", "Planning, tool use, memory and multi-agent systems."),
               ("mcp", "MCP & Tool Use", "plug", "Model Context Protocol and connecting models to real tools."),
               ("tools", "Tools", "tools", "Frameworks and platforms for building AI applications."),
           ])]),
    "statistics": ("Statistics", "bar-chart-line",
                   "The language of uncertainty: probability, inference and modeling, built from first principles.",
                   [("Foundations", [
                       ("descriptive", "Descriptive Statistics", "table", "Center, spread, shape and summarising data honestly."),
                       ("probability", "Probability", "dice-5", "Random variables, expectation and the rules of chance."),
                       ("distributions", "Distributions", "graph-up", "Normal, binomial, Poisson and friends, with intuition."),
                   ]),
                    ("Inference", [
                       ("inference", "Statistical Inference", "search", "Estimation, confidence intervals and sampling."),
                       ("hypothesis-testing", "Hypothesis Testing", "check2-square", "p-values, power and choosing the right test."),
                       ("regression", "Regression", "graph-up-arrow", "Linear, logistic and generalized linear models."),
                       ("bayesian", "Bayesian Methods", "diagram-3", "Priors, posteriors and probabilistic reasoning."),
                   ]),
                    ("Applied", [
                       ("time-series", "Time Series", "clock-history", "Trend, seasonality and forecasting."),
                       ("experimentation", "Experimentation & A/B Testing", "toggles", "Designing and reading controlled experiments."),
                   ])]),
    "software": ("Software", "code-slash",
                 "The languages and tools every data and AI practitioner uses daily.",
                 [("Languages", [
                     ("python", "Python", "filetype-py", "Idiomatic Python, NumPy, pandas and packaging."),
                     ("sql", "SQL", "database", "Queries, joins, window functions and performance."),
                     ("r", "R", "r-circle", "R for statistics, tidyverse and visualization."),
                 ]),
                  ("Workflow", [
                     ("git", "Git & GitHub", "git", "Version control, branching and collaboration."),
                     ("linux", "Linux & CLI", "terminal", "The command line skills that save hours."),
                     ("big-data", "Spark & Big Data", "hdd-stack", "Distributed processing with Spark and friends."),
                 ])]),
    "deployment": ("Deployment", "rocket-takeoff",
                   "From notebook to production: packaging, serving, scaling and keeping models healthy.",
                   [("Build", [
                       ("tools", "Tools", "tools", "FastAPI, MLflow, BentoML and the serving toolkit."),
                       ("mlops", "MLOps", "arrow-repeat", "CI/CD, experiment tracking and reproducible pipelines."),
                       ("containers", "Docker & Containers", "box-seam", "Packaging models so they run anywhere."),
                       ("cloud", "Cloud Platforms", "cloud", "AWS, GCP and Azure options for ML workloads."),
                   ]),
                    ("Operate", [
                       ("scale", "Scale", "arrows-angle-expand", "Batching, autoscaling, caching and cost control."),
                       ("monitoring", "Monitoring", "activity", "Drift, latency, quality and alerting."),
                       ("maintenance", "Maintenance", "wrench-adjustable", "Retraining, dependency care and incident handling."),
                       ("update", "Updates & Versioning", "arrow-up-circle", "Safe rollouts, model registries and rollback."),
                   ])]),
    "resources": ("Resources", "journal-bookmark",
                  "Quick references and curated material to learn faster.",
                  [("Learn", [
                      ("learning-paths", "Learning Paths", "signpost-split", "Ordered reading lists from beginner to production."),
                      ("cheat-sheets", "Cheat Sheets", "file-earmark-text", "One-page summaries of formulas and commands."),
                      ("glossary", "Glossary", "book", "Plain-language definitions of key terms."),
                  ]),
                   ("Explore", [
                      ("papers", "Paper Notes", "journal-text", "Readable summaries of influential papers."),
                      ("datasets", "Datasets", "collection", "Free, high-quality datasets for practice."),
                  ])]),
}


def writable(p: Path) -> bool:
    return (not p.exists()) or AUTO in p.read_text(encoding="utf-8") or "Coming soon." in p.read_text(encoding="utf-8")


def card(href, icon, title, desc):
    return (f'<a class="topic-card" href="{href}">'
            f'<span class="topic-icon"><i class="bi bi-{icon}"></i></span>'
            f'<span class="topic-body"><span class="topic-title">{title}</span>'
            f'<span class="topic-desc">{desc}</span></span>'
            f'<i class="bi bi-arrow-right topic-arrow"></i></a>')


EMPTY = '<div class="listing-no-matching">New articles are on the way. Check back soon.</div>'


def has_articles(folder: Path, recursive: bool) -> bool:
    pattern = "**/*.qmd" if recursive else "*.qmd"
    return any(p.name != "index.qmd" for p in folder.glob(pattern))


def strip_listing(page: str, listing_id: str) -> str:
    """Remove the listing block when a folder has no articles yet (avoids empty-listing warnings)."""
    head, rest = page.split("listing:", 1)
    rest = rest.split("\n---\n", 1)[1]
    page = head + "---\n" + rest
    return page.replace("::: {#" + listing_id + "}\n:::", EMPTY)


def section_page(slug, title, icon, tagline, groups):
    blocks = []
    for gname, topics in groups:
        cards = "\n".join(card(f"{t[0]}/index.html", t[2], t[1], t[3]) for t in topics)
        blocks.append(f'<h2 class="group-title">{gname}</h2>\n<div class="topic-grid">\n{cards}\n</div>')
    return f"""---
title: "{title}"
description: "{tagline}"
page-layout: full
toc: false
title-block-style: none
listing:
  id: section-latest
  contents:
    - "**/*.qmd"
    - "!**/index.qmd"
  type: grid
  grid-columns: 3
  sort: "date desc"
  max-items: 6
  fields: [title, description, categories, reading-time, date]
  categories: false
  filter-ui: false
  sort-ui: false
---
{AUTO}

```{{=html}}
<header class="section-hero" data-section="{slug}">
  <span class="section-hero-icon"><i class="bi bi-{icon}"></i></span>
  <p class="eyebrow">MLStation · {title}</p>
  <h1>{title}</h1>
  <p class="lead">{tagline}</p>
</header>
{chr(10).join(blocks)}
<h2 class="group-title">Latest articles</h2>
```

::: {{#section-latest}}
:::
"""


def topic_page(section_title, slug, title, icon, desc):
    return f"""---
title: "{title}"
description: "{desc}"
page-layout: full
toc: false
title-block-style: none
listing:
  id: topic-articles
  contents:
    - "*.qmd"
    - "!index.qmd"
  type: default
  sort: "date desc"
  fields: [title, description, categories, reading-time, date]
  categories: false
  filter-ui: false
  sort-ui: false
---
{AUTO}

```{{=html}}
<header class="section-hero compact">
  <span class="section-hero-icon"><i class="bi bi-{icon}"></i></span>
  <p class="eyebrow">{section_title}</p>
  <h1>{title}</h1>
  <p class="lead">{desc}</p>
</header>
```

::: {{#topic-articles}}
:::
"""


if __name__ == "__main__":
    n = 0
    for s, (title, icon, tagline, groups) in SITE.items():
        p = Path(s) / "index.qmd"
        p.parent.mkdir(parents=True, exist_ok=True)
        if writable(p):
            page = section_page(s, title, icon, tagline, groups)
            if not has_articles(Path(s), recursive=True):
                page = strip_listing(page, "section-latest")
            p.write_text(page, encoding="utf-8"); n += 1
        for _, topics in groups:
            for slug, t, ic, d in topics:
                tp = Path(s) / slug / "index.qmd"
                tp.parent.mkdir(parents=True, exist_ok=True)
                if writable(tp):
                    page = topic_page(title, slug, t, ic, d)
                    if not has_articles(tp.parent, recursive=False):
                        page = strip_listing(page, "topic-articles")
                    tp.write_text(page, encoding="utf-8"); n += 1
    print(f"Done. {n} landing pages written.")
